import type { Task, Agent } from '@/types/task'

// Mock agents
export const mockAgents: Agent[] = [
  {
    name: 'Makima',
    role: 'Control Devil',
    specialization: 'Executive orchestration',
    currentWorkload: 60,
    activeTasks: ['task-1', 'task-2', 'task-3'],
    skills: ['coordination', 'strategy', 'monitoring'],
  },
  {
    name: 'Power',
    role: 'Blood Fiend',
    specialization: 'Task execution',
    currentWorkload: 80,
    activeTasks: ['task-4', 'task-5', 'task-6', 'task-7'],
    skills: ['execution', 'combat', 'speed'],
  },
  {
    name: 'Aki',
    role: 'Devil Hunter',
    specialization: 'Research & Analysis',
    currentWorkload: 40,
    activeTasks: ['task-8', 'task-9'],
    skills: ['research', 'analysis', 'contracts'],
  },
  {
    name: 'Denji',
    role: 'Chainsaw Devil',
    specialization: 'Simple tasks',
    currentWorkload: 20,
    activeTasks: ['task-10'],
    skills: ['simple-tasks', 'destruction'],
  },
  {
    name: 'Himeno',
    role: 'Ghost Devil Contractor',
    specialization: 'Support operations',
    currentWorkload: 30,
    activeTasks: ['task-11'],
    skills: ['support', 'ghost-contract', 'investigation'],
  },
  {
    name: 'Kobeni',
    role: 'Rookie Agent',
    specialization: 'General tasks',
    currentWorkload: 100,
    activeTasks: ['task-12', 'task-13', 'task-14', 'task-15', 'task-16'],
    skills: ['driving', 'navigation', 'panic'],
  },
]

// Mock tasks
export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Set up monitoring dashboard',
    description: 'Create a real-time monitoring dashboard for agent activities and task status',
    status: 'progress',
    priority: 'high',
    assignee: 'Makima',
    category: 'development',
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-01-16T14:30:00Z',
    dueDate: '2024-01-20',
  },
  {
    id: 'task-2',
    title: 'Review security protocols',
    description: 'Audit and update security protocols for the task management system',
    status: 'pending',
    priority: 'critical',
    assignee: 'Makima',
    category: 'testing',
    createdAt: '2024-01-14T10:00:00Z',
    updatedAt: '2024-01-14T10:00:00Z',
    dependencies: ['task-1'],
  },
  {
    id: 'task-3',
    title: 'Coordinate team meeting',
    description: 'Schedule and facilitate weekly team coordination meeting',
    status: 'completed',
    priority: 'medium',
    assignee: 'Makima',
    category: 'documentation',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-12T16:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Implement task filtering',
    description: 'Add filtering capabilities to the task list component',
    status: 'progress',
    priority: 'high',
    assignee: 'Power',
    category: 'development',
    createdAt: '2024-01-15T11:00:00Z',
    updatedAt: '2024-01-16T09:00:00Z',
    relatedFiles: ['src/components/task-list.tsx', 'src/hooks/use-filters.ts'],
  },
  {
    id: 'task-5',
    title: 'Fix pagination bug',
    description: 'Resolve issue with pagination not updating correctly on filter change',
    status: 'blocked',
    priority: 'high',
    assignee: 'Power',
    category: 'development',
    createdAt: '2024-01-14T14:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    dependencies: ['task-4'],
  },
  {
    id: 'task-6',
    title: 'Add keyboard shortcuts',
    description: 'Implement keyboard navigation and shortcuts for power users',
    status: 'pending',
    priority: 'low',
    assignee: 'Power',
    category: 'development',
    createdAt: '2024-01-16T09:00:00Z',
    updatedAt: '2024-01-16T09:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Performance optimization',
    description: 'Optimize rendering performance for large task lists',
    status: 'progress',
    priority: 'medium',
    assignee: 'Power',
    category: 'development',
    createdAt: '2024-01-13T15:00:00Z',
    updatedAt: '2024-01-16T11:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Research agent patterns',
    description: 'Study and document common agent interaction patterns',
    status: 'progress',
    priority: 'medium',
    assignee: 'Aki',
    category: 'research',
    createdAt: '2024-01-12T09:00:00Z',
    updatedAt: '2024-01-16T08:00:00Z',
  },
  {
    id: 'task-9',
    title: 'Analyze competitor tools',
    description: 'Research and compare features of similar task management tools',
    status: 'pending',
    priority: 'low',
    assignee: 'Aki',
    category: 'research',
    createdAt: '2024-01-15T16:00:00Z',
    updatedAt: '2024-01-15T16:00:00Z',
    dueDate: '2024-01-25',
  },
  {
    id: 'task-10',
    title: 'Update user documentation',
    description: 'Revise and expand user documentation for new features',
    status: 'pending',
    priority: 'medium',
    assignee: 'Denji',
    category: 'documentation',
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
  {
    id: 'task-11',
    title: 'Set up CI/CD pipeline',
    description: 'Configure continuous integration and deployment for the project',
    status: 'completed',
    priority: 'high',
    assignee: 'Himeno',
    category: 'development',
    createdAt: '2024-01-08T14:00:00Z',
    updatedAt: '2024-01-12T17:00:00Z',
  },
  {
    id: 'task-12',
    title: 'Write unit tests',
    description: 'Create comprehensive unit tests for core components',
    status: 'progress',
    priority: 'high',
    assignee: 'Kobeni',
    category: 'testing',
    createdAt: '2024-01-14T11:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
  {
    id: 'task-13',
    title: 'Fix login redirect',
    description: 'Resolve issue with redirect after login on mobile devices',
    status: 'blocked',
    priority: 'critical',
    assignee: 'Kobeni',
    category: 'development',
    createdAt: '2024-01-15T13:00:00Z',
    updatedAt: '2024-01-16T08:00:00Z',
    dependencies: ['task-12'],
  },
  {
    id: 'task-14',
    title: 'Add error boundaries',
    description: 'Implement error boundaries for better error handling',
    status: 'pending',
    priority: 'medium',
    assignee: 'Kobeni',
    category: 'development',
    createdAt: '2024-01-16T08:00:00Z',
    updatedAt: '2024-01-16T08:00:00Z',
  },
  {
    id: 'task-15',
    title: 'Review pull requests',
    description: 'Review and provide feedback on pending pull requests',
    status: 'pending',
    priority: 'high',
    assignee: 'Kobeni',
    category: 'development',
    createdAt: '2024-01-16T09:00:00Z',
    updatedAt: '2024-01-16T09:00:00Z',
  },
  {
    id: 'task-16',
    title: 'Update dependencies',
    description: 'Update project dependencies to latest stable versions',
    status: 'pending',
    priority: 'low',
    assignee: 'Kobeni',
    category: 'development',
    createdAt: '2024-01-16T11:00:00Z',
    updatedAt: '2024-01-16T11:00:00Z',
  },
  // Unassigned tasks
  {
    id: 'task-17',
    title: 'Design onboarding flow',
    description: 'Create user-friendly onboarding experience for new users',
    status: 'pending',
    priority: 'medium',
    assignee: '',
    category: 'design',
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
    dueDate: '2024-01-30',
  },
  {
    id: 'task-18',
    title: 'Implement dark mode',
    description: 'Add dark mode theme support to the application',
    status: 'pending',
    priority: 'low',
    assignee: '',
    category: 'development',
    createdAt: '2024-01-15T15:00:00Z',
    updatedAt: '2024-01-15T15:00:00Z',
  },
  {
    id: 'task-19',
    title: 'API documentation',
    description: 'Create comprehensive API documentation for external integrations',
    status: 'pending',
    priority: 'high',
    assignee: '',
    category: 'documentation',
    createdAt: '2024-01-14T12:00:00Z',
    updatedAt: '2024-01-14T12:00:00Z',
    dueDate: '2024-01-28',
  },
  {
    id: 'task-20',
    title: 'Accessibility audit',
    description: 'Perform WCAG 2.1 AA compliance audit and fix issues',
    status: 'pending',
    priority: 'high',
    assignee: '',
    category: 'testing',
    createdAt: '2024-01-13T10:00:00Z',
    updatedAt: '2024-01-13T10:00:00Z',
  },
]